In [4]:
import pinocchio
import numpy as np 
import time 
import pymanopt 
from pymanopt import manifolds, optimizers, tools, core
from pymanopt.core.problem  import Problem

from utils import *
import networkx as nx
from scipy import optimize
from scipy.optimize import Bounds

import tqdm

LOWER = "lower_limit"
UPPER = "upper_limit"
BOUNDED = "bounded"
BELOW = "below"
ABOVE = "above"
TYPE = "type"
OBSTACLE = "obstacle"
ROBOT = "robot"
END_EFFECTOR = "end_effector"
RADIUS = "radius"
DIST = "weight"
POS = "pos"
BASE = "base"
ROOT = None
ANCHOR = "anchor"
UNDEFINED = None

deg2rad = np.pi/180.
rad2deg = 180./np.pi

scale = 1

%load_ext autoreload
%autoreload 2

In [5]:
def create_base_graph(model,data,axis_length):

    trans_z = pinocchio.SE3(np.eye(3),np.array([0,0,axis_length]))

    q_init = pinocchio.neutral(model)
    pinocchio.forwardKinematics(model,data,q_init)
    
    robot_name = model.names[1]
    ROOT = robot_name

    base = nx.empty_graph()

    for idx, (name, oMi) in enumerate(zip(model.names, data.oMi)):
        if idx > 1:
            cur, aux_cur = (name, name+'_tilde')
            cur_pos, aux_cur_pos = (
                oMi.translation*scale,
                pinocchio.SE3.act(pinocchio.SE3(oMi.rotation,oMi.translation*scale),trans_z).translation,
            )
            #print(name,cur_pos,aux_cur_pos)
            dist = np.linalg.norm(cur_pos - aux_cur_pos)

            # Add nodes for joint and edge between them
            base.add_nodes_from(
                [(cur, {POS: cur_pos}), (aux_cur, {POS: aux_cur_pos})]
            )
            base.add_edge(
                cur, aux_cur, **{DIST: dist, LOWER: dist, UPPER: dist, BOUNDED: [], ANCHOR: False}
            )

            # If there exists a preceeding joint, connect it to new
            if idx != 0:
                pred, aux_pred = (model.names[idx-1], model.names[idx-1]+'_tilde')
                for u in [pred, aux_pred]:
                    for v in [cur, aux_cur]:
                        dist = np.linalg.norm(
                            base.nodes[u][POS] - base.nodes[v][POS]
                        )
                        base.add_edge(
                            u,
                            v,
                            **{DIST: dist, LOWER: dist, UPPER: dist, BOUNDED: [], ANCHOR: False},
                        )
        elif idx == 1:
            #print(name,oMi.translation)
            base = nx.DiGraph(
                [
                    (robot_name, "x"),
                    (robot_name, "y"),
                    (robot_name, robot_name+'_tilde'),
                    ("x", "y"),
                    ("y", robot_name+'_tilde'),
                    (robot_name+'_tilde' ,"x"),
                ]
            )
            base.add_nodes_from(
                [
                    ("x", {POS: np.array([axis_length, 0, 0]) + oMi.translation*scale, TYPE: [BASE]}),
                    ("y", {POS: np.array([0, -axis_length, 0]) + oMi.translation*scale, TYPE: [BASE]}),
                    (robot_name, {POS: oMi.translation*scale, TYPE: [ROBOT, BASE]}),
                    (robot_name+'_tilde', {POS: np.array([0, 0, axis_length]) + oMi.translation*scale, TYPE: [ROBOT, BASE]}),
                ]
            )
            for u, v in base.edges():
                base[u][v][DIST] = np.linalg.norm(base.nodes[u][POS] - base.nodes[v][POS])
                base[u][v][LOWER] = base[u][v][DIST]
                base[u][v][UPPER] = base[u][v][DIST]
                base[u][v][ANCHOR] = True
                base[u][v][BOUNDED] = []

    # Set node type to robot
    nx.set_node_attributes(base, [ROBOT], TYPE)
    base.nodes[ROOT][TYPE] = [ROBOT, BASE]
    base.nodes[ROOT + '_tilde'][TYPE] = [ROBOT, BASE]

    return base

In [34]:
axis_length = 0.2*scale
urdf_filename="GraphIK/graphik/robots/urdfs/kuka_iiwr.urdf"
# 'GraphIK/graphik/robots/urdfs/panda_arm.urdf'

model    = pinocchio.buildModelFromUrdf(urdf_filename)
data     = model.createData()

G = create_base_graph(model,data,axis_length)


In [7]:
nx.get_node_attributes(G,POS)

{'lbr_iiwa_joint_1': array([0.    , 0.    , 0.1575]),
 'x': array([0.2   , 0.    , 0.1575]),
 'y': array([ 0.    , -0.2   ,  0.1575]),
 'lbr_iiwa_joint_1_tilde': array([0.    , 0.    , 0.3575]),
 'lbr_iiwa_joint_2': array([0.  , 0.  , 0.36]),
 'lbr_iiwa_joint_2_tilde': array([-4.13646214e-14,  2.00000000e-01,  3.60000000e-01]),
 'lbr_iiwa_joint_3': array([ 2.07103964e-25, -1.00133990e-12,  5.64500000e-01]),
 'lbr_iiwa_joint_3_tilde': array([ 4.13646214e-14, -1.00131770e-12,  7.64500000e-01]),
 'lbr_iiwa_joint_4': array([ 4.45703796e-14, -1.00131597e-12,  7.80000000e-01]),
 'lbr_iiwa_joint_4_tilde': array([ 8.5935001e-14, -2.0000000e-01,  7.8000000e-01]),
 'lbr_iiwa_joint_5': array([ 8.27292428e-14, -9.78656600e-14,  9.64500000e-01]),
 'lbr_iiwa_joint_5_tilde': array([1.24093864e-13, 1.86078980e-12, 1.16450000e+00]),
 'lbr_iiwa_joint_6': array([1.27299622e-13, 2.01258560e-12, 1.18000000e+00]),
 'lbr_iiwa_joint_6_tilde': array([4.45703796e-14, 2.00000000e-01, 1.18000000e+00]),
 'lbr_iiwa

In [8]:

def norm(x):
    return x/max(np.linalg.norm(x),10**-9)

def goal_graph(model, data, G, axis_length, position, direction = None, anchor = True):
    
    end_effector = [model.names[-1]]
    if direction is not None:
        end_effector.append(model.names[-1]+'_tilde')

    list_nodes_base = ['x','y',model.names[1],model.names[1]+'_tilde']

    for i, cur_end_effector in enumerate(end_effector):
        pos_end = position

        if direction is not None and i == 1:
            pos_end = pos_end + direction*axis_length
        
        G.nodes[cur_end_effector][POS] = pos_end

        for cur_base in list_nodes_base:
            
            if not((i == 1) and (len(end_effector)==1)):
                dist = np.linalg.norm(pos_end-G.nodes[cur_base][POS])

                G.add_edge(
                            cur_base, cur_end_effector, **{DIST: dist, LOWER: dist, UPPER: dist, BOUNDED: [], ANCHOR: anchor}
                        )
    
    if anchor:

        list_edges_anchor = []
        list_other_edges = []
        new_edge_order  = []
        A_anchor = []

        for key ,anch_ in nx.get_edge_attributes(G,ANCHOR).items():

            if anch_:
                list_edges_anchor.append(key)
                A_anchor.append(norm(G.nodes[key[1]][POS]- G.nodes[key[0]][POS]))
                #print(key,' : ',norm(G.nodes[key[1]][POS]- G.nodes[key[0]][POS]))
            else:
                list_other_edges.append(key)
        new_edge_order = list_edges_anchor.copy() #.extend(list_other_edges)

        for e in list_other_edges:
            new_edge_order.append(e)

        A_anchor = np.array(A_anchor).transpose()
        
    else:

        list_edges_anchor = []
        list_other_edges = [e for e in G.edges()]

        new_edge_order = list_other_edges
        A_anchor = []

    n = len(list_other_edges)
    n_anchor = len(list_edges_anchor)

    weight = nx.get_edge_attributes(G, DIST)
    D = np.diag([weight[i] for i in new_edge_order])

    C = incidence_matrix_(G,oriented=True, edgelist=new_edge_order).toarray()
    C = np.array(C)

    Y_init = np.zeros((3,n))

    for i, e in enumerate(list_other_edges):
        i = i 
        p1 = G.nodes[e[0]][POS]
        p2 = G.nodes[e[1]][POS]
        Y_init[:,i] = (p2-p1)/max(np.linalg.norm(p2-p1),10**-9)

    if anchor:
        Y_init = [A_anchor,Y_init]
    return G, list_edges_anchor, list_edges_anchor, new_edge_order, n,n_anchor, A_anchor, D,C, Y_init

In [9]:
def simple_IK(d,C,D,A_,n, n_anchor,max_iter,ind=None,W=None,Y_init=None,use_rand=False):
    if  W is None:
        W = np.eye(D.shape[0])
    if n_anchor > 0:    
        if d > 3:
            A = np.zeros((d,n_anchor))
            A[:3,:] = A_[:3,:]
        else:
            if A_.shape[0] == d:
                A = A_
            elif A_.shape[0] > d:
                A = A_[:d,:]
            else:
                A = np.zeros((d,n_anchor))
                A[:3,:] = A_[:3,:]

        manifold_ = manifolds.Product([manifolds.ConstantFactory(A) , manifolds.Oblique(d,n)])
    else:
        manifold_ = manifolds.Oblique(d,n)

    Q2 = -D@(W@C.transpose()@np.linalg.pinv(C@W@C.transpose()))@C@W@D
    Q1 = D@W@D

    if n_anchor > 0:
        zero = np.zeros_like(A)
        @pymanopt.function.numpy(manifold_)
        def cost(A,Y_):
            #print(A.shape,Y_.shape)
            Y = np.concatenate([A,Y_],axis=1)
            return np.trace(Q1 + Q2@Y.transpose()@Y) 

        @pymanopt.function.numpy(manifold_)
        def euclidean_gradient(A,Y_):
            Y = np.concatenate([A,Y_],axis=1)
            grad = 2*Q2[n_anchor:,:]@Y.transpose()
            return [zero,grad.transpose() ]
                                
        @pymanopt.function.numpy(manifold_)
        def euclidean_hessian(A,Y_,U_A, U):
            U_ = np.concatenate([U_A,U],axis=1)
            hess = 2*Q2[n_anchor:,:]@U_.transpose()
            return [zero,hess.transpose()]
    else:
        @pymanopt.function.numpy(manifold_)
        def cost(Y):
            return np.trace(Q1 + Q2@Y.transpose()@Y) 

        @pymanopt.function.numpy(manifold_)
        def euclidean_gradient(Y):
            grad = 2*Q2@Y.transpose()
            return grad.transpose() 
                                
        @pymanopt.function.numpy(manifold_)
        def euclidean_hessian(Y,U):
            hess = 2*Q2@U.transpose()
            return hess.transpose()


    problem = Problem(manifold=manifold_, 
                      cost=cost,
                      euclidean_gradient=euclidean_gradient, 
                      euclidean_hessian=euclidean_hessian,
                      )

    optimizer = optimizers.TrustRegions(max_iterations=max_iter,use_rand=use_rand,min_gradient_norm=10**-12,verbosity=0)
    #print(n_anchor)
    if  Y_init is None:
        Y_init_ = manifold_.random_point()
    elif n_anchor > 1:
        if Y_init[0].shape[0] == d:
            #print(1)
            Y_init_ = Y_init
        elif Y_init[0].shape[0] < d:
            #print(2)
            Y_init_ = np.zeros((d,n))
            Y_init_[:Y_init[0].shape[0],:] = Y_init[1]
            Y_init_ = [A, Y_init_]
        else:
            #print(3)
            if len(Y_init) == 2:
                U,S,V = np.linalg.svd(Y_init[1],full_matrices=False)
            else:
                U,S,V = np.linalg.svd(Y_init,full_matrices=False)
            Y_init_ = [A, U[:d,:d]@np.diag(S)[:d,:]@V/np.maximum(np.linalg.norm(U[:d,:d]@np.diag(S)[:d,:]@V,axis=0),10**-9)]
    else:
        if Y_init.shape[0] == d:
            #print(1)
            Y_init_ = Y_init
        elif Y_init.shape[0] < d:
            #print(2)
            Y_init_ = np.zeros((d,n))
            Y_init_[:Y_init.shape[0],:] = Y_init
        else:
            #print(3)
            U,S,V = np.linalg.svd(Y_init,full_matrices=False)
            Y_init_ = U[:d,:d]@np.diag(S)[:d,:]@V/np.maximum(np.linalg.norm(U[:d,:d]@np.diag(S)[:d,:]@V,axis=0),10**-9)
    
    Y_star = optimizer.run(problem,initial_point=Y_init_).point

    return Y_star

In [10]:
def direction_to_position(Y,C,D,data):
    #print(Y.shape, C.shape, D.shape)
    X = np.linalg.pinv(C@C.transpose())@C@D@Y.transpose()
    #print(X)
    X = X - X[0,:] + data.oMi[1].translation*scale
    
    #if X[0,0]<0:
      #  X = -X
    
    v = X[1,:] - X[0,:]
    R = rotation_matrix_from_vectors(v/np.linalg.norm(v),e1/np.linalg.norm(e1))
    X = (X - X[0,:])@R.transpose() + X[0,:]

    v = X[2,:] - X[0,:]
    R = rotation_matrix_from_vectors(v/np.linalg.norm(v),-e2/np.linalg.norm(e2))
    X = (X - X[0,:])@R.transpose() + X[0,:]
    flip = 1

    if X[3,2]<axis_length:
        flip = -1
    v = X[2,:] - X[0,:]
    R = np.diag((1,1,flip))
    X = (X - X[0,:])@R.transpose() + X[0,:]

    return X

def rotation_matrix_from_vectors(vec1, vec2):
    """ Find the rotation matrix that aligns vec1 to vec2
    :param vec1: A 3d "source" vector
    :param vec2: A 3d "destination" vector
    :return mat: A transform matrix (3x3) which when applied to vec1, aligns it with vec2.
    """
    a, b = (vec1 / np.linalg.norm(vec1)).reshape(3), (vec2 / np.linalg.norm(vec2)).reshape(3)
    v = np.cross(a, b)
    c = np.dot(a, b)
    s = np.linalg.norm(v)
    kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    rotation_matrix = np.eye(3) + kmat + kmat.dot(kmat) * ((1 - c) / (s ** 2))
    return rotation_matrix

In [11]:
def skew(x):
    """
    Creates a skew symmetric matrix from vector x
    """
    X = np.array([[0, -x[2], x[1]], [x[2], 0, -x[0]], [-x[1], x[0], 0]])
    return X


def joint_variables(model,data, G, T_final, axis_length):
    """
    Finds the set of decision variables corresponding to the
    graph realization G.

    :param G: networkx.DiGraph with known vertex positions
    :param T_final: poses of end-effectors in case two final frames aligned along z
    :returns: Dictionary of joint angles
    :rtype: Dict[str, float]
    """
    tol = 1e-10
    
    T = {}
    T[ROOT] = data.oMi[1] #G.nodes[model.names[1]][POS]

    pinocchio.forwardKinematics(model,data,pinocchio.neutral(model))
    T_zero = {name: oMi for name, oMi in zip(model.names, data.oMi)}

    trans_z = pinocchio.SE3(np.eye(3),np.array([0,0,axis_length]))
    
    # resolve scale
    x_hat = G.nodes["x"][POS] - G.nodes[model.names[1]][POS]
    y_hat = G.nodes["y"][POS] - G.nodes[model.names[1]][POS]
    z_hat = G.nodes[model.names[1]+'_tilde'][POS] - G.nodes[model.names[1]][POS]

    # resolve rotation and translation
    x = norm(x_hat)
    y = norm(y_hat)
    z = norm(z_hat)
    R = np.vstack((x, -y, z)).T
    B = pinocchio.SE3(R, np.zeros((3,))) #G.nodes[ROOT][POS])

    omega_z = skew(np.array([0,0,1]))

    theta = {}
    
    for idx, (name, oMi) in enumerate(zip(model.names, data.oMi)):
        if idx > 1:
            cur, aux_cur = (name, name+'_tilde')
            pred, aux_pred = (model.names[idx-1], model.names[idx-1]+'_tilde')

            T_prev = T[pred]
            
            T_prev_0 = T_zero[pred] # previous p xf at 0
            T_0 = T_zero[cur] # cur p xf at 0
            T_0_q = pinocchio.SE3.act(T_zero[cur],trans_z) # cur q xf at 0
            T_rel = pinocchio.SE3.act(pinocchio.SE3.inverse(T_prev_0),T_0) # relative xf
            ps_0 = pinocchio.SE3.act(pinocchio.SE3.inverse(T_prev_0),T_0).translation # relative xf
            qs_0 = pinocchio.SE3.act(pinocchio.SE3.inverse(T_prev_0),T_0_q).translation # rel q xf

            # predicted p and q expressed in previous frame
            p = pinocchio.SE3.act(pinocchio.SE3.inverse(B),G.nodes[cur][POS])
            qnorm = G.nodes[cur][POS] + (
                G.nodes[aux_cur][POS] - G.nodes[cur][POS]
            ) / np.linalg.norm(G.nodes[aux_cur][POS] - G.nodes[cur][POS])
            q = pinocchio.SE3.act(pinocchio.SE3.inverse(B),qnorm)
            #print(T_prev)
            ps = pinocchio.SE3.inverse(T_prev).rotation.dot(p - T_prev.translation)  # in prev. joint frame
            qs = pinocchio.SE3.inverse(T_prev).rotation.dot(q - T_prev.translation)  # in prev. joint frame

            theta[cur] = np.arctan2(-qs_0.dot(omega_z).dot(qs), qs_0.dot(omega_z.dot(omega_z.T)).dot(qs))
            rot_axis_z = pinocchio.SE3(Rot_z(theta[cur]),np.zeros((3,)))
            T[cur] = pinocchio.SE3.act(pinocchio.SE3.act(T_prev,rot_axis_z),T_rel)

    # if the rotation axis of final joint is aligned with ee frame z axis,
    # get angle from EE pose if available
    #if ((T_final is not None) and (la.norm(cross(T_rel.trans, np.asarray([0, 0, 1]))) < tol)):
     #   T_th = (T[cur]).inv().dot(T_final[ee]).as_matrix()
     #   theta[ee] = wraptopi(theta[ee] +  arctan2(T_th[1, 0], T_th[0, 0]))

    return theta

In [38]:
def root_angle_limits(G,model,data,axis_length):
    upper_limits = np.minimum(-model.lowerPositionLimit,model.upperPositionLimit)
    limited_joints = [] 
    i = 2
    T1 = data.oMi[1]
    base_names = ["x", "y"]
    names = [model.names[i],model.names[i]+'_tilde']
    T_axis = pinocchio.SE3(np.eye(3),np.array([0,0,axis_length]))

    for base_node in base_names:
        for node in names:
            T0 = pinocchio.SE3.Identity()
            T0.translation = G.nodes[base_node][POS]
            if node == model.names[i]:
                T2 = data.oMi[i]
            else:
                T2 = pinocchio.SE3.act(data.oMi[i],T_axis)

            N = T1.rotation[0:3, 2]
            C = T1.translation + (N.dot(T2.translation - T1.translation)) * N
            r = np.linalg.norm(T2.translation - C)
            P = T0.translation
            d_max, d_min = max_min_distance_revolute(r, P, C, N)
            d = np.linalg.norm(T2.translation - T0.translation)

            if d_max == d_min:
                limit = False
            elif d == d_max:
                limit = BELOW
            elif d == d_min:
                limit = ABOVE
            else:
                limit = None

            if limit:
                T_rel = pinocchio.SE3.act(pinocchio.SE3.inverse(T1),data.oMi[i])
                if node != model.names[i]:
                    T_rel = pinocchio.SE3.act(T_rel,T_axis)

                d_limit = np.linalg.norm(
                    pinocchio.SE3.act(pinocchio.SE3.act(T1,pinocchio.SE3(Rot_z(upper_limits[0]),np.zeros((3,)))),T_rel).translation
                    - T0.translation
                )

                if limit == ABOVE:
                    d_max = d_limit
                else:
                    d_min = d_limit
                limited_joints += [model.names[i]]  # joint at p0 is limited
            print(base_node, node)
            G.add_edge(base_node, node)
            if d_max == d_min:
                G[base_node][node][DIST] = d_max
            G[base_node][node][BOUNDED] = [limit]
            G[base_node][node][UPPER] = d_max
            G[base_node][node][LOWER] = d_min

    return G

In [39]:
G_ = root_angle_limits(G,model,data,axis_length)


x lbr_iiwa_joint_2
x lbr_iiwa_joint_2_tilde
y lbr_iiwa_joint_2
y lbr_iiwa_joint_2_tilde


In [42]:
nx.get_edge_attributes(G,BOUNDED)

{('lbr_iiwa_joint_1', 'x'): [],
 ('lbr_iiwa_joint_1', 'y'): [],
 ('lbr_iiwa_joint_1', 'lbr_iiwa_joint_1_tilde'): [],
 ('lbr_iiwa_joint_1', 'lbr_iiwa_joint_2'): [],
 ('lbr_iiwa_joint_1', 'lbr_iiwa_joint_2_tilde'): [],
 ('x', 'y'): [],
 ('x', 'lbr_iiwa_joint_2'): [False],
 ('x', 'lbr_iiwa_joint_2_tilde'): [None],
 ('y', 'lbr_iiwa_joint_1_tilde'): [],
 ('y', 'lbr_iiwa_joint_2'): [False],
 ('y', 'lbr_iiwa_joint_2_tilde'): ['below'],
 ('lbr_iiwa_joint_1_tilde', 'x'): [],
 ('lbr_iiwa_joint_1_tilde', 'lbr_iiwa_joint_2'): [],
 ('lbr_iiwa_joint_1_tilde', 'lbr_iiwa_joint_2_tilde'): [],
 ('lbr_iiwa_joint_2', 'lbr_iiwa_joint_2_tilde'): [],
 ('lbr_iiwa_joint_2', 'lbr_iiwa_joint_3'): [],
 ('lbr_iiwa_joint_2', 'lbr_iiwa_joint_3_tilde'): [],
 ('lbr_iiwa_joint_2_tilde', 'lbr_iiwa_joint_3'): [],
 ('lbr_iiwa_joint_2_tilde', 'lbr_iiwa_joint_3_tilde'): [],
 ('lbr_iiwa_joint_3', 'lbr_iiwa_joint_3_tilde'): [],
 ('lbr_iiwa_joint_3', 'lbr_iiwa_joint_4'): [],
 ('lbr_iiwa_joint_3', 'lbr_iiwa_joint_4_tilde'): [],

In [16]:
q0 = np.array([30,35,10,-40,90,0,0])*np.pi/180
#q0 = np.array([0,0,0,0,0,0,0])*np.pi/180
#q0 = pinocchio.randomConfiguration(model)
pinocchio.framesForwardKinematics(model,data,q0)
position = data.oMi[-1].translation*scale #np.array([200,0,500])/1000
direction = data.oMi[-1].rotation@np.array([0,0,1])

print(position, direction)
ROOT = model.names[1]

G1, list_edges_anchor, list_edges_anchor, new_edge_order, n,n_anchor, A_anchor, D,C, Y_init_ = goal_graph(model, data, G, axis_length, 
                                                                                                 position, direction = direction, anchor = True)



[0.58081515 0.39732814 0.83122999] [0.77377923 0.57562804 0.26442024]


In [17]:
theta = joint_variables(model,data, G1, data.oMi[-1], axis_length)
theta = np.array([theta_ for key, theta_ in theta.items()])
theta,q0

(array([-0.00000000e+00,  6.94475657e-14, -2.91679776e-14,  9.40722830e-14,
         4.84860683e-14,  1.63298542e+00]),
 array([ 0.52359878,  0.61086524,  0.17453293, -0.6981317 ,  1.57079633,
         0.        ,  0.        ]))

In [18]:
pinocchio.forwardKinematics(model,data,np.concatenate([theta,np.zeros((1,))]))
#pinocchio.forwardKinematics(model,data,theta)
print(position,direction)
data.oMi[-1]

[0.58081515 0.39732814 0.83122999] [0.77377923 0.57562804 0.26442024]


  R =
   -0.062149  4.46706e-12     0.998067
-4.70726e-12            1 -4.76872e-12
   -0.998067 -4.99443e-12    -0.062149
  p =   0.0808434 2.02294e-12     1.17497

In [19]:
theta = joint_variables(model,data, G1, data.oMi[-1], axis_length)
theta = np.array([theta_ for key, theta_ in theta.items()])
pinocchio.forwardKinematics(model,data,np.concatenate([theta,np.zeros((1,))]))
print(np.linalg.norm(position-data.oMi[-1].translation))
print(np.linalg.norm(direction-data.oMi[-1].rotation@np.array([0,0,1])))

0.725255663136422
0.6987847147316119


In [20]:
nx.get_node_attributes(G1,POS)


{'lbr_iiwa_joint_1': array([0.    , 0.    , 0.1575]),
 'x': array([0.2   , 0.    , 0.1575]),
 'y': array([ 0.    , -0.2   ,  0.1575]),
 'lbr_iiwa_joint_1_tilde': array([0.    , 0.    , 0.3575]),
 'lbr_iiwa_joint_2': array([0.  , 0.  , 0.36]),
 'lbr_iiwa_joint_2_tilde': array([-4.13646214e-14,  2.00000000e-01,  3.60000000e-01]),
 'lbr_iiwa_joint_3': array([ 2.07103964e-25, -1.00133990e-12,  5.64500000e-01]),
 'lbr_iiwa_joint_3_tilde': array([ 4.13646214e-14, -1.00131770e-12,  7.64500000e-01]),
 'lbr_iiwa_joint_4': array([ 4.45703796e-14, -1.00131597e-12,  7.80000000e-01]),
 'lbr_iiwa_joint_4_tilde': array([ 8.5935001e-14, -2.0000000e-01,  7.8000000e-01]),
 'lbr_iiwa_joint_5': array([ 8.27292428e-14, -9.78656600e-14,  9.64500000e-01]),
 'lbr_iiwa_joint_5_tilde': array([1.24093864e-13, 1.86078980e-12, 1.16450000e+00]),
 'lbr_iiwa_joint_6': array([1.27299622e-13, 2.01258560e-12, 1.18000000e+00]),
 'lbr_iiwa_joint_6_tilde': array([4.45703796e-14, 2.00000000e-01, 1.18000000e+00]),
 'lbr_iiwa

In [21]:
W = np.diag(np.concatenate([np.ones(n_anchor),np.ones(n)]))
#Y_D10 = simple_IK(3,C,D,A_,n, n_anchor,max_iter=1000,W=W,Y_init=None)
#Y_D5 = simple_IK(5,C,D,A_anchor,n, n_anchor,max_iter=1000,W=W,Y_init=Y_init_) #[A_,Y_init])
Y_D4 = simple_IK(4,C,D,A_anchor,n, n_anchor,max_iter=2000,W=W,Y_init=None,use_rand =False)
Y_D3 = simple_IK(3,C,D,A_anchor,n, n_anchor,max_iter=2000,W=W,Y_init=Y_D4,use_rand =False)

In [22]:
Y_star = Y_D3
e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

if len(Y_star) == 2:
    X = direction_to_position(np.concatenate([Y_star[0],Y_star[1]],axis=1),C,D,data)
else:
    X = direction_to_position(Y_star,C,D,data)

print(X)
print(np.linalg.norm(X[-2,:]-position))
print(np.linalg.norm((X[-1,:]-X[-2,:])/axis_length-direction))


for idx,node in enumerate(G1.nodes()):
    G1.nodes[node][POS] = X[idx,:]


[[ 0.00000000e+00  0.00000000e+00  1.57500000e-01]
 [ 2.00000000e-01  2.51486926e-12  1.57500000e-01]
 [ 1.15418648e-28 -2.00000000e-01  1.57500000e-01]
 [ 1.27602625e-08 -1.27352405e-08  3.57500026e-01]
 [ 2.61028408e-05  1.49398446e-05  3.59999921e-01]
 [ 9.94547603e-02 -1.73518753e-01  3.59999983e-01]
 [ 1.01745217e-01  5.82964338e-02  5.27561086e-01]
 [ 2.01366609e-01  1.15376060e-01  6.91321598e-01]
 [ 2.09114120e-01  1.19824403e-01  7.03988042e-01]
 [ 3.32766196e-01 -3.59722379e-02  6.83069847e-01]
 [ 3.51585714e-01  2.26322607e-01  7.52980435e-01]
 [ 5.06089825e-01  3.41874610e-01  8.05670535e-01]
 [ 5.18090604e-01  3.50784616e-01  8.09774598e-01]
 [ 6.02472866e-01  3.19391650e-01  6.31185361e-01]
 [ 5.80815189e-01  3.97328096e-01  8.31229995e-01]
 [ 7.35571043e-01  5.12453706e-01  8.84114043e-01]]
6.038195253793447e-08
4.2598550329169046e-08


In [23]:
count_success = 0
err_pos = []
err_or = []
scale = 1

axis_length = 0.4*scale
urdf_filename="GraphIK/graphik/robots/urdfs/kuka_iiwr.urdf"
# 'GraphIK/graphik/robots/urdfs/panda_arm.urdf'

model    = pinocchio.buildModelFromUrdf(urdf_filename)
data     = model.createData()

G = create_base_graph(model,data,axis_length)

for i in tqdm.tqdm(range(1)):
    q0 = pinocchio.randomConfiguration(model)
    pinocchio.framesForwardKinematics(model,data,q0)
    position = data.oMi[-1].translation*scale #np.array([200,0,500])/1000
    direction = None#data.oMi[-1].rotation@np.array([0,0,1])

    #print(position, direction)

    G1, list_edges_anchor, list_edges_anchor, new_edge_order, n,n_anchor, A_anchor, D,C, Y_init_ = goal_graph(model, data, G, axis_length, 
                                                                                                 position, direction = direction, anchor = True)
    
    W = np.diag(1./np.diag(D)**2)#np.diag(np.concatenate([np.ones(n_anchor),np.ones(n)]))
    Y_D5 = simple_IK(5,C,D,A_anchor,n, n_anchor,max_iter=100,W=W,Y_init=None,use_rand =False)
    Y_D4 = simple_IK(4,C,D,A_anchor,n, n_anchor,max_iter=300,W=W,Y_init=Y_D5,use_rand =False)
    Y_D3 = simple_IK(3,C,D,A_anchor,n, n_anchor,max_iter=2000,W=W,Y_init=Y_D4,use_rand =False)

    
    Y_star = Y_D3

    if len(Y_star) == 2:
        #print(ANCHOR)
        X = direction_to_position(np.concatenate([Y_star[0],Y_star[1]],axis=1),C,D,data)
    else:
        X = direction_to_position(Y_star,C,D,data)
    #print((X[-2,:]-X[-1,:])/np.linalg.norm((X[-2,:]-X[-1,:])),direction)
        
    for idx,node in enumerate(G1.nodes()):
        G1 .nodes[node][POS] = X[idx,:]

    theta = joint_variables(model,data, G1, data.oMi[-1], axis_length)
    theta = np.array([theta_ for key, theta_ in theta.items()])
    pinocchio.forwardKinematics(model,data,np.concatenate([theta,np.zeros((1,))]))
    err_pos.append(np.linalg.norm(position-data.oMi[-1].translation))
    #err_or.append(np.linalg.norm(direction-data.oMi[-1].rotation@np.array([0,0,1])))
    #err_or.append(np.linalg.norm((X[-1,:]-X[-2,:])/np.linalg.norm((X[-2,:]-X[-1,:]))-direction))
    #err_pos.append(np.linalg.norm(X[-2,:]-position))
    #print(X[3,:])


100%|██████████| 1/1 [00:12<00:00, 12.23s/it]


In [24]:
print(max(err_pos))#,max(err_or))
#sum(np.array(err_or)<10**-5)


6.988000704308717e-06
